modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "structurepalettes"
version = "${version}"
displayName = "Structure Palettes"
authors = "orlouge"
description = '''
A mod that randomly replaces blocks in structures
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
