modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "structurepalettes"
version = "${version}"
displayName = "Structure Palettes"
authors = "orlouge"
description = '''
A mod that randomly replaces blocks in structures
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
